eight04/ComicCrawler

comiccrawler/util.py
=> Add: escape more characters in safefilepath

.pylintrc, comiccrawler/analyzer.py, comiccrawler/gui/main_window.py, comiccrawler/gui/table.py, comiccrawler/mission.py, comiccrawler/mission_manager.py, comiccrawler/util.py
=> Add: last_update attr, sortable table

comiccrawler/mods/dm5.py
=> add hk.dm5.com

comiccrawler/mods/youhui.py
=> Add: youhui module

comiccrawler/grabber.py, comiccrawler/mods/__init__.py, comiccrawler/mods/seemh.py
Fixes #131.
Fixes #132.
@DummySYSTEM Could you test if this branch works? You can install this branch with:
```
pip install https://github.com/eight04/ComicCrawler/archive/dev-grabber-cooldown.zip
```
=> Add: implement grabber_cooldown

comiccrawler/mods/mh160.py
=> Add: mh160 module

comiccrawler/mods/dm5.py, comiccrawler/util.py
=> Fix: dm5 new layout

comiccrawler/crawler.py, comiccrawler/mods/toho.py
=> Add: toho module

comiccrawler/mods/xznj120.py
=> Add: new domain 36rm.cn for xznj module

comiccrawler/mods/hhxiee.py
=> Add: new domain hheess.com for hhcomic

README.rst, comiccrawler/mods/toho.py
=>  Add: new domain www.tohomh123.com for toho 

comiccrawler/mods/exh.py
igneous is required for ex site
=> Add: cookie_igneous config for exh

comiccrawler/mods/gufeng.py
=> Fix: new domain for gufeng

comiccrawler/mods/artstation.py
=> Fix: handle 403 error in artstation

comiccrawler/mods/facebook.py
=> Fix: failed to switch page in fb

comiccrawler/mods/manhuaren.py
=> Add: manhuaren module

comiccrawler/mods/xznj120.py, comiccrawler/mods/youhui.py
=> Fix: ignore empty episodes in youhui

comiccrawler/mods/pixiv.py
=> Fix: enable error handler for 404 err in pixiv

comiccrawler/mods/manhuadui.py
=> Add: manhuadui module

README.rst, comiccrawler/config.py, comiccrawler/gui/main_window.py
=> Add: autocheck_interval option

comiccrawler/mods/bilibili.py
=> Add: bilibili module

comiccrawler/mods/_177pic.py
=> Add: 177pic module

comiccrawler/crawler.py, comiccrawler/episode.py, comiccrawler/mods/pixiv.py
=> Fix: globalInitData is not used anymore in pixiv

README.rst, comiccrawler/analyzer.py, comiccrawler/crawler.py, comiccrawler/mods/sankaku_beta.py
=> Add: sankaku beta, redirecthandler hook, allow LastPageError in get_episodes

comiccrawler/mods/instagram.py
=> Add: instagram

comiccrawler/mods/pixiv.py
=> Add: support pixiv search page

README.rst, comiccrawler/module_grabber.py
=> Add: verify option

comiccrawler/mods/seemh.py
=> Fix: params are changed in seemh

comiccrawler/mods/nijie.py
=> Fix: dojin issue in nijie

README.rst, comiccrawler/crawler.py, comiccrawler/mods/manhuabei_m.py, setup.cfg
=> Add: manhuabei, no_referer tag. Bump python to 3.6

comiccrawler/mods/setnmh.py
=> Add: setnmh module

comiccrawler/mods/nico.py
=> Fix: failed to fetch nico source

comiccrawler/mods/sankaku.py, comiccrawler/mods/sankaku_beta.py
=> Fix: sankaku api is changed

comiccrawler/mods/deviantart.py
=> Fix: deviantart

comiccrawler/mods/oh.py
=> Fix: paging issue in ohmh

comiccrawler/mods/qq.py
=> Fix: qq nonce

comiccrawler/crawler.py, comiccrawler/mods/cartoonmad.py
=> Change: send referer when fetching html. Fix cartoonmad error

comiccrawler/mods/gelbooru.py
=> Fix: empty ep error in gelbooru

comiccrawler/mods/pixiv.py
=> Fix: cannot analyze search page in pixiv

comiccrawler/download_manager.py, comiccrawler/mods/instagram.py
=> Change: stop downloading if all available missions fail

comiccrawler/mods/dmzj.py
=> Fix: download hidden manga on dmzj

comiccrawler/mods/copy.py, requirements-lock.txt, setup.cfg
=> Add: copymanga module

comiccrawler/mods/seemh.py, requirements-lock.txt, setup.cfg
=> Fix: analyze error in seemh, add new domain www.mhgui.com

comiccrawler/mods/danbooru.py
=> Fix: now danbooru requires curl

comiccrawler/mods/copy.py, pyrightconfig.json
=> Add: new copy domain, pyright config

comiccrawler/mods/twitter.py
=> Fix: twitter analyze error

comiccrawler/mods/seemh.py
=> Fix: servs has been moved to configjs (seemh)

comiccrawler/mods/seemh.py, comiccrawler/util.py
=> Fix: seemh server detection

comiccrawler/mods/seemh.py, requirements-lock.txt, setup.cfg
=> Fix: drop lzstring

comiccrawler/mods/cartoonmad.py
=> Fix: failed matching image in cartoonmad

comiccrawler/mods/seemh.py
=> Fix: LZString vm error

comiccrawler/grabber.py, comiccrawler/mods/aacomic.py, comiccrawler/mods/hhxiee.py, comiccrawler/mods/iibq.py, comiccrawler/mods/seemh.py
=> Fix: wrong protocol in seemh. Failed downloading webp images

comiccrawler/mods/eight.py, comiccrawler/mods/facebook.py, comiccrawler/mods/sankaku_beta.py
=> Fix: eight
